### ISSUE TITLE
Error running tests with Django 1.11 relation "auth_user" does not exist

### ISSUE THREAD

**Issue by mwaz** [pinax/django-user-accounts#278] opened 2018-01-11 17:35 UTC
I updated my project from 1.10 to 1.11, and tests failed with the above issue.
I've tried a number of solutions to fix this, and I did narrow it down to django-user-accounts. 
i have not been able to run my tests even on downgrading back to django 1.10

Been searching for any fix for the error and none is involved

**Comment by grahamu** [comment] 2018-01-11 23:23
@mwaz I just verified locally that django-user-accounts tests pass on all supported Django/Python combinations:
  
<img width="285" alt="d-u-a test suite results" src="https://user-images.githubusercontent.com/130456/34852159-7dfffdbe-f6ea-11e7-962e-a76f91f90776.png">

Django project has ended support for v1.10. Reference Supported Versions in https://www.djangoproject.com/download/.

Django v1.11 incorporated many changes; perhaps something in the [v1.11 release notes](https://docs.djangoproject.com/en/2.0/releases/1.11/#django-1-11-release-notes) can explain your issue.

If none of this helps and you feel django-user-accounts is failing somehow, please either provide more detail about your test failures, or better yet, submit a pull request with a test showing the problem. Thanks!

**Comment by grahamu** [comment] 2018-01-30 00:08
@mwaz please open another ticket if you find this problem persists. Closing this now as unable to reproduce.

**Closed by grahamu** 2018-01-30 00:08 UTC
